variable "env" {}
variable "tags" {}
variable "vpc" {}
variable "default_vpc_id" {}
variable "default_route_table" {}
variable "docdb" {}
variable "rds" {}
variable "elasticache" {}
variable "rabbitmq" {}